src/main/java/com/vishwakarma/provilac/model/Product.java
package com.vishwakarma.provilac.model;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PostPersist;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * 
 * @author Reshma
 *
 */

@Entity
@Table(name="Product",uniqueConstraints=@UniqueConstraint(columnNames={"id"}))
public class Product extends BaseEntity{
	
	//TODO: Remove Category, and take it as separate model
	
	private String code;
	
	@NotNull
	@NotEmpty
	private String name;
	
	private double price, tax;
	
	private String colorCode;
	
	@Column(columnDefinition="MediumText")
	private String description;  
	
	@ManyToOne
	@JoinColumn(name="categoryId",nullable=false,referencedColumnName="id")
	private Category category;
	
	private String productPicUrl;
	
	@Transient
	private byte[] picData;
	
	@Transient
	private String tempFileName;
	
	@Column(columnDefinition="tinyint(1) default '0'")
	private boolean isAvailableSubscription, isAvailableOneTimeOrder;

	private String productBannerUrl, productCartPicUrl, productListPicUrl, productDetailsPicUrl;
	
	@ElementCollection(fetch=FetchType.LAZY)
	private Map<Integer, Double> pricingMap = new HashMap<Integer, Double>();
	
	@Transient
	private byte[] bannerData, productCartPicData, productListPicData, productDetailsPicData;
	
	@Transient
	private String bannerFileName, productCartPicFileName, productListPicFileName, productDetailsPicFileName;
	
	
	@PostPersist
	public void populateCode() {
		setCode("PR-" + getId());
	}
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}
	
	public String getColorCode() {
		return colorCode;
	}

	public void setColorCode(String colorCode) {
		this.colorCode = colorCode;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public double getTax() {
		return tax;
	}

	public void setTax(double tax) {
		this.tax = tax;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getProductPicUrl() {
		return productPicUrl;
	}

	public void setProductPicUrl(String productPicUrl) {
		this.productPicUrl = productPicUrl;
	}

	public byte[] getPicData() {
		return picData;
	}

	public void setPicData(byte[] picData) {
		this.picData = picData;
	}

	public String getTempFileName() {
		return tempFileName;
	}

	public void setTempFileName(String tempFileName) {
		this.tempFileName = tempFileName;
	}

	public boolean isAvailableSubscription() {
		return isAvailableSubscription;
	}

	public void setAvailableSubscription(boolean isAvailableSubscription) {
		this.isAvailableSubscription = isAvailableSubscription;
	}

	public boolean isAvailableOneTimeOrder() {
		return isAvailableOneTimeOrder;
	}

	public void setAvailableOneTimeOrder(boolean isAvailableOneTimeOrder) {
		this.isAvailableOneTimeOrder = isAvailableOneTimeOrder;
	}

	public String getProductBannerUrl() {
		return productBannerUrl;
	}

	public void setProductBannerUrl(String productBannerUrl) {
		this.productBannerUrl = productBannerUrl;
	}

	public Map<Integer, Double> getPricingMap() {
		return pricingMap;
	}

	public void setPricingMap(Map<Integer, Double> pricingMap) {
		this.pricingMap = pricingMap;
	}

	public byte[] getBannerData() {
		return bannerData;
	}

	public void setBannerData(byte[] bannerData) {
		this.bannerData = bannerData;
	}

	public String getBannerFileName() {
		return bannerFileName;
	}

	public void setBannerFileName(String bannerFileName) {
		this.bannerFileName = bannerFileName;
	}

	public String getProductCartPicUrl() {
		return productCartPicUrl;
	}

	public String getProductListPicUrl() {
		return productListPicUrl;
	}

	public String getProductDetailsPicUrl() {
		return productDetailsPicUrl;
	}

	public byte[] getProductCartPicData() {
		return productCartPicData;
	}

	public byte[] getProductListPicData() {
		return productListPicData;
	}

	public byte[] getProductDetailsPicData() {
		return productDetailsPicData;
	}

	public String getProductCartPicFileName() {
		return productCartPicFileName;
	}

	public String getProductListPicFileName() {
		return productListPicFileName;
	}

	public String getProductDetailsPicFileName() {
		return productDetailsPicFileName;
	}

	public void setProductCartPicUrl(String productCartPicUrl) {
		this.productCartPicUrl = productCartPicUrl;
	}

	public void setProductListPicUrl(String productListPicUrl) {
		this.productListPicUrl = productListPicUrl;
	}

	public void setProductDetailsPicUrl(String productDetailsPicUrl) {
		this.productDetailsPicUrl = productDetailsPicUrl;
	}

	public void setProductCartPicData(byte[] productCartPicData) {
		this.productCartPicData = productCartPicData;
	}

	public void setProductListPicData(byte[] productListPicData) {
		this.productListPicData = productListPicData;
	}

	public void setProductDetailsPicData(byte[] productDetailsPicData) {
		this.productDetailsPicData = productDetailsPicData;
	}

	public void setProductCartPicFileName(String productCartPicFileName) {
		this.productCartPicFileName = productCartPicFileName;
	}

	public void setProductListPicFileName(String productListPicFileName) {
		this.productListPicFileName = productListPicFileName;
	}

	public void setProductDetailsPicFileName(String productDetailsPicFileName) {
		this.productDetailsPicFileName = productDetailsPicFileName;
	}
	
	 
}

src/main/java/com/vishwakarma/provilac/controller/ProductController.java
package com.vishwakarma.provilac.controller;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.core.env.Environment;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.FileCopyUtils;
import org.springframework.validation.BindingResult;
import org.springframework.validation.DataBinder;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.multipart.MultipartFile;

import com.vishwakarma.provilac.api.ApiResponse;
import com.vishwakarma.provilac.dto.ProductDTO;
import com.vishwakarma.provilac.exception.ProvilacException;
import com.vishwakarma.provilac.model.Category;
import com.vishwakarma.provilac.model.Product;
import com.vishwakarma.provilac.model.Role;
import com.vishwakarma.provilac.model.User;
import com.vishwakarma.provilac.mvc.validator.ProductValidator;
import com.vishwakarma.provilac.property.editor.CategoryPropertyEditor;
import com.vishwakarma.provilac.repository.CategoryRepository;
import com.vishwakarma.provilac.repository.UserRepository;
import com.vishwakarma.provilac.service.CategoryService;
import com.vishwakarma.provilac.service.ProductService;
import com.vishwakarma.provilac.service.UserService;
import com.vishwakarma.provilac.utils.AppConstants;
import com.vishwakarma.provilac.utils.AppFileUtils;
import com.vishwakarma.provilac.utils.DateHelper;
import com.vishwakarma.provilac.utils.EncryptionUtil;
import com.vishwakarma.provilac.web.RequestInterceptor;

@Controller
@SessionAttributes(value = { "id", "version", "retUrl", "retPage" })
public class ProductController {

	@Resource
	private ProductValidator productValidator;

	@Resource
	private ProductService productService;

	@Resource
	private UserService userService;
	
	@Resource
	private UserRepository userRepository;
	
	@Resource
	private CategoryService categoryService;
	
	@Resource
	private CategoryRepository categoryRepository;
	
	@Resource
	private Environment environment;
	
	@Resource
	private AppFileUtils appFileUtils;
	
	@Resource	
	private RequestInterceptor requestInterceptor;
	
	@InitBinder(value = "product")
	public void initBinder(WebDataBinder binder) {
		binder.setDisallowedFields("id", "version");
		CustomDateEditor customDateEditor = new CustomDateEditor(new SimpleDateFormat(DateHelper.DATE_FORMAT), true);
		binder.registerCustomEditor(Date.class, customDateEditor);
		binder.registerCustomEditor(Category.class, new CategoryPropertyEditor(categoryRepository));
		binder.setValidator(productValidator);
	}

	private Model populateModelForAdd(Model model, Product product) {
		User loggedInUser = userService.getLoggedInUser();
		model.addAttribute("product", product);
		model.addAttribute("today", DateHelper.getFormattedDate(new Date()));
		model.addAttribute("categories", categoryService.getAllCategorys(loggedInUser, false, false));
		return model;
	}

	@RequestMapping(value = "/admin/product/add")
	public String addProduct(Model model) {
		User loggedInUser = userService.getLoggedInUser();
		if(loggedInUser.hasAnyRole(Role.ROLE_ACCOUNTANT)||loggedInUser.hasAnyRole(Role.ROLE_INTERN)||loggedInUser.hasAnyRole(Role.ROLE_CCE)){
			return "redirect:/admin/denied";
		}
		model = populateModelForAdd(model, new Product());
		return "admin-pages/product/add";
	}

	@RequestMapping(value = "/admin/product/add", method = RequestMethod.POST)
	public String productAdd(Product product, 
									BindingResult formBinding, 
									Model model,
									@RequestParam(required = true, value="productPic")MultipartFile productPic,
									@RequestParam(required = true, value="productBan")MultipartFile productBanner,
									@RequestParam(required = true, value="productCart")MultipartFile productCartPic,
									@RequestParam(required = true, value="productList")MultipartFile productListPic,
									@RequestParam(required = true, value="productDetails")MultipartFile productDetailsPic){
		
		productValidator.validate(product, formBinding);
		
		if (null != productPic && !productPic.isEmpty()) {
			String contentType = productPic.getContentType();
			if (!contentType.contains("image/")) {
				formBinding.addError(new FieldError("product", "productPicUrl", "Please select valid  product pic"));
			} else if (productPic.getSize() > 5242880) { // Maximum size = 5MB
				formBinding.addError(new FieldError("product", "productPicUrl", "Please select product image Picture less than 5MB"));
			}
			try {
				product.setPicData(productPic.getBytes());
				product.setTempFileName(productPic.getOriginalFilename());
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			formBinding.addError(new FieldError("product", "productPicUrl", "Please select valid product Pic"));
		}
		
		if (null != productBanner && !productBanner.isEmpty()) {
			String contentType = productBanner.getContentType();
			if (!contentType.contains("image/")) {
				formBinding.addError(new FieldError("product", "productBannerUrl", "Please select valid  product banner"));
			} else if (productBanner.getSize() > 5242880) { // Maximum size = 5MB
				formBinding.addError(new FieldError("product", "productBannerUrl", "Please select product banner image Picture less than 5MB"));
			}
			try {
				product.setBannerData(productBanner.getBytes());
				product.setBannerFileName(productBanner.getOriginalFilename());
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			formBinding.addError(new FieldError("product", "productBannerUrl", "Please select valid product banner"));
		}
		
		if (null != productCartPic && !productCartPic.isEmpty()) {
			String contentType = productCartPic.getContentType();
			if (!contentType.contains("image/")) {
				formBinding.addError(new FieldError("product", "productCartPicUrl", "Please select valid  product cart pic"));
			} else if (productCartPic.getSize() > 5242880) { // Maximum size = 5MB
				formBinding.addError(new FieldError("product", "productCartPicUrl", "Please select product cart image Picture less than 5MB"));
			}
			try {
				product.setProductCartPicData(productCartPic.getBytes());
				product.setProductCartPicFileName(productCartPic.getOriginalFilename());
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			formBinding.addError(new FieldError("product", "productCartPicUrl", "Please select valid product cart Pic"));
		}
		
		if (null != productListPic && !productListPic.isEmpty()) {
			String contentType = productListPic.getContentType();
			if (!contentType.contains("image/")) {
				formBinding.addError(new FieldError("product", "productListPicUrl", "Please select valid  product list pic"));
			} else if (productListPic.getSize() > 5242880) { // Maximum size = 5MB
				formBinding.addError(new FieldError("product", "productListPicUrl", "Please select product list image Picture less than 5MB"));
			}
			try {
				product.setProductListPicData(productListPic.getBytes());
				product.setProductListPicFileName(productListPic.getOriginalFilename());
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			formBinding.addError(new FieldError("product", "productListPicUrl", "Please select valid product list Pic"));
		}
		
		if (null != productDetailsPic && !productDetailsPic.isEmpty()) {
			String contentType = productDetailsPic.getContentType();
			if (!contentType.contains("image/")) {
				formBinding.addError(new FieldError("product", "productDetailsPicUrl", "Please select valid  product details pic"));
			} else if (productDetailsPic.getSize() > 5242880) { // Maximum size = 5MB
				formBinding.addError(new FieldError("product", "productDetailsPicUrl", "Please select product details image Picture less than 5MB"));
			}
			try {
				product.setProductDetailsPicData(productDetailsPic.getBytes());
				product.setProductDetailsPicFileName(productDetailsPic.getOriginalFilename());
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			formBinding.addError(new FieldError("product", "productDetailsPicUrl", "Please select valid product details Pic"));
		}
		
		if (formBinding.hasErrors()) {
			model = populateModelForAdd(model, product);
			return "admin-pages/product/add";
		}
		User loggedInUser = userService.getLoggedInUser();
		productService.createProduct(product, loggedInUser, true,false);
		String message = "Product added successfully";
		return "redirect:/admin/product/list?message=" + message;
	}

	@RequestMapping(value = "/admin/product/list")
	public String getProductList(Model model, 
										@RequestParam(defaultValue = "1") Integer pageNumber,
										@RequestParam(required = false) String message, 

src/main/webapp/WEB-INF/pages/admin-pages/product/import.jsp
<%@ include file="/taglibs.jsp"%>
<html>
<head>
<title>Provilac - Import Products</title>
</head>
<c:url value="/admin/product/import" var="importUrl" />
<body>
	<sec:authorize access="isAnonymous()">
	    <c:redirect url="/login"/>
	</sec:authorize>
	<form id="importProduct" method="post" action="${importUrl}" enctype="multipart/form-data">
		<div>
		    <c:if test="${not empty message}">
		        <div id="message" class="success">${message}</div>  
		    </c:if>
		</div>
		<fieldset>
			<h3 class="page-header">Product - Import</h3>
			<div class="input-group width-xlarge">
				<span class="input-group-addon">Excel File*</span>
				<input name="file" id="file" type="file" class="form-control" />
			</div>
			<br>
		</fieldset>
	
		<a href="<c:url value="/assets/import-templates/Products_Import_Template.xlsx" />">Download import template files from here!!</a>
		<br/>
		<br>
		<button class="btn btn-info" type="submit">Import</button>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a class="btn btn-danger" href="javascript:history.back(1)">Cancel </a>
	</form>
</body>

src/main/webapp/WEB-INF/pages/admin-pages/product/nav.jsp
<%@ include file="/taglibs.jsp"%>
<c:url value="/admin/product/add" var="productAdd" />
<c:url value="/admin/product/list" var="productList" />
<c:url value="/admin/product/import" var="productImport" />
<body>

<div class="row  border-bottom white-bg dashboard-header">
	<div class="span4">
	<sec:authorize access="hasAnyAuthority('ROLE_SUPER_ADMIN','ROLE_ADMIN')">
		<a class="btn btn-primary" href="${productAdd}">Add New Product</a>&nbsp;
		<a class="btn btn-primary" href="${productImport}">Import Product</a>&nbsp;
	</sec:authorize>
	<form class="form-inline pull-right" action="${urlBase}" action="get" role="form">
	  <input type="text" class="form-control width-xlarge" name="searchTerm" id="searchTerm" placeholder="search">
	  <button type="submit" class="btn btn-success">Search</button>
	  <a class="btn btn-info" href="${urlBase}">View All</a>
	</form>
	</div>
	
</div>

src/main/webapp/WEB-INF/pages/admin-pages/product/show.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ include file="/taglibs.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Provilac - Product</title>

<script type="text/javascript">
$(document).ready(function() {
	displayImage();
});
function displayImage(){
	var productId = ${product.id};
	var html ='<img id="displayImage" src="<c:url value="/restapi/getProductPicture?id=' + productId+'"/>" border="0" height="real_height" width="real_width" onload="resizeImg(this,300, 500);">';
	$('#displayImageDiv').append(html);
}

function resizeImg(img, height, width) {
	img.height = height;
    img.width = width;
}

</script>
</head>
<body>
	<div class="row">
		<div class="col-lg-12">
			<h3 class="page-header">Product- Details</h3>
		</div>
	</div>
	<div class="panel panel-primary" id="primary-info">
		<div class="panel-heading">
			<h3 class="panel-title">Primary Info</h3>
		</div>
		<div class="panel-body" style="margin-left: 10px;">
			<div class="row">
				<label class="col-md-2">Name</label>
				<p class="col-md-2">${product.name}</p>
				<label class="col-md-2">Price</label>
				<p class="col-md-2">${product.price}</p>
				<label class="col-md-2">Category</label>
				<p class="col-md-2">${product.category.name}</p>
			</div>
			
			
			<div class="row">
				<label class="col-md-2">Tax</label>
				<p class="col-md-2">${product.tax}</p>
				<label class="col-md-2">Description</label>
				<p class="col-md-4">${product.description}</p>
				
			</div>
			<div class="row">
				<label class="col-md-3">Available For Subscription</label>
					<c:choose>
						<c:when test="${product.availableSubscription}"><p class="col-md-2">Yes</p></c:when>
						<c:otherwise><p class="col-md-2">No</p></c:otherwise>
					</c:choose>
				<label class="col-md-3">Available For One Time Order</label>
				<c:choose>
						<c:when test="${product.availableOneTimeOrder}"><p class="col-md-2">Yes</p></c:when>
						<c:otherwise><p class="col-md-2">No</p></c:otherwise>
					</c:choose>
			</div>
			<div class="row"  style="margin-left: 5px" id ="imageBorder" >
			<label >Image</label> 
			<div id ="displayImageDiv"></div>
				
			</div>
			
		</div>
	</div>


	<div class="panel panel-info" id="base-info">
		<div class="panel-heading">
			<h3 class="panel-title">Base Info</h3>
		</div>
		<div class="panel-body" style="margin-left: 10px;">
			<div class="row">
				<label class="col-md-2">Created By</label>
				<p class="col-md-4">${product.createdBy}</p>
				<label class="col-md-2">Created Date</label>
				<p class="col-md-2">
					<fmt:formatDate value="${product.createdDate}" pattern="dd-MM-yyy hh:mm:ss a" />
				</p>
			</div>
			<div class="row">
				<label class="col-md-2">Last Modified By</label>
				<p class="col-md-4">${product.lastModifiedBy}</p>
				<label class="col-md-2">Last Modified Date</label>
				<p class="col-md-2">
					<fmt:formatDate value="${product.modifiedDate}" pattern="dd-MM-yyy hh:mm:ss a" />
				</p>
			</div>
		</div>
	</div>
	<a class="btn btn-success" href="javascript:history.back(1)">Ok</a>
</body>
</html>